### ISSUE TITLE
Error("expected dedent, near \"user:\\n    password: test\\n    username: test\\n\"")

### ISSUE THREAD

**Issue by rawlingsj** [behrang/YamlSwift#25]
I've got some valid yaml that I'm importing from my filesystem, I'd like to parse it but YamlSwift throws an error.  I'm not 100% sure I'm doing everything right mind.

```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    username: test
- name: staging
  user:
    password: test
    username: test
```

```
readString = try NSString(contentsOfFile: filePath, encoding: NSUTF8StringEncoding) as String

if (readString != "") {
     let value = Yaml.load(readString)
     if (value.error != ""){
          print(value.error)
     }
     print(value)
}

```

results in 

```
Error("expected dedent, near \"user:\\n    password: test\\n    username: test\\n\"")
```

**Comment by behrang** [comment]
Your input Yaml is invalid. You have a `clusters` array with first element `cluster` and second element `name`. But `user` has no meaning there. If you want it to be the third element, you need a `-` before it. Or if you want it to be a key of root dictionary, you have to dedent it.

**Comment by rawlingsj** [comment]
FWIW the yaml is generated by Kubernetes CLI and http://www.yamllint.com/ certainly says it's valid.

**Comment by rawlingsj** [comment]
Thanks for the advice though, I'll modify the yaml before loading it.

**Comment by behrang** [comment]
Yaml lint converted your Yaml to this:
```
--- 
apiVersion: v1
clusters: 
  - 
    cluster: 
      insecure-skip-tls-verify: true
      username: test
  - 
    name: staging
    user: 
      password: test
      username: test
```

In this form, it is valid. Let me check this more.

**Comment by behrang** [comment]
@rawlingsj I was wrong. Your Yaml is correct. I'm working on a fix.

**Comment by rawlingsj** [comment]
Ok that's great, thanks @behrang

**Comment by rawlingsj** [comment]
Hi - I wondered if you'd had a chance to look at this?  

If it helps I've added below (removing sensitive info) the full yaml I'm looking to parse, it's generated by the kubernetes and openshift CLI tools [kubectl](http://kubernetes.io/docs/user-guide/kubectl-overview/) / [oc](https://github.com/openshift/origin/blob/master/docs/cli.md).  YAMLlint validates it but I appreciate that may not be the best source to check things.

```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://172.1.1.1:8443
  name: 172-1-1-1:8443
- cluster:
    insecure-skip-tls-verify: true
    server: https://1.1.1.1:8443
  name: 192-1-1-1:8443
- cluster:
    server: https://api:443
  name: api-rh-idev-openshift-com:443
- cluster:
    insecure-skip-tls-verify: true
    server: https://kubernetes.io
  name: beast
- cluster:
    insecure-skip-tls-verify: true
    server: https://kubernetes.io
  name: cd
- cluster:
    insecure-skip-tls-verify: true
    server: https://104.1.1.1
  name: demo
- cluster:
    server: http://172.1.1.1:8080
  name: local
- cluster:
    certificate-authority: /Users/cheese/.minishift/apiserver.crt
    server: https://192.1.1.1:8443
  name: minishift
- cluster:
    insecure-skip-tls-verify: true
    server: https://cheese:8443
  name: cheese:8443
contexts:
- context:
    cluster: beast
    namespace: default
    user: beast
  name: beast
- context:
    cluster: cd
    namespace: cd
    user: cd
  name: cd
- context:
    cluster: 172-1-1-1:8443
    namespace: default
    user: admin/172-1-1-1:8443
  name: default/172-1-1-1:8443/cheese
- context:
    cluster: 192-1-1-1:8443
    namespace: default
    user: admin/192-1-1-1:8443
  name: default/192-1-1-1:8443/cheese
- context:
    cluster: cheese-io:8443
    namespace: default
    user: admin/cheese-io:8443
  name: default/cheese-io:8443/cheese
- context:
    cluster: demo
    namespace: default
    user: demo
  name: demo
- context:
    cluster: api:443
    namespace: cheese
    user: cheese/api:443
  name: cheese/api:443/cheese
- context:
    cluster: beast
    namespace: kube-system
    user: kube
  name: kube-system
- context:
    cluster: ""
    user: ""
  name: local
- context:
    cluster: minishift
    user: minishift
  name: minishift
current-context: beast
kind: Config
preferences: {}
users:
- name: cheese/172-1-1-1:8443
  user:
    token: blah
- name: cheese/192-1-1-1:8443
  user:
    token: blah
- name: cheese/cheese-io:8443
  user:
    token: blah
- name: beast
  user:
    password: cheese
    username: cheese
- name: cd
  user:
    password: cheese
    username: cheese
- name: demo
  user:
    password: cheese
    username: cheese
- name: kube
  user:
    password: cheese
    username: cheese
- name: minishift
  user:
    client-certificate: /Users/cheese/.minishift/apiserver.crt
    client-key: /Users/cheese/.minishift/apiserver.key
- name: cheese/api:443
  user:
    token: blah
```

**Comment by behrang** [comment]
Hi. I confirm that this is a problem of `YamlSwift`. Current implementation is hard to change and maintain. To solve this, I've recently created another project [SwiftParsec](https://github.com/behrang/SwiftParsec) which is a parser combinator library. The next step is using it to create a parser for Yaml. Currently I'm very busy, but when I have some free time, I'll work on it.

**Comment by behrang** [comment]
After 6 months, the new branch `parsec` is ready and is working with your test documents.

I would appreciate your feedback.

**Comment by sttz** [comment]
I had the same error when I included an array of hashes in a Yaml file that I generate in Python and then read using YamlSwift. Updating to the `parsec` branch fixed it!

Switching to the branch was a bit of a pain, though. I was using Carthage but the branch doesn't have an Xcode project and the Swift 3 package manager doesn't (yet?) support branches. So I cloned it manually, used `swift package generate-xcodeproj`, added the generated Xcode project as a dependency by dropping it into my Xcode project and added it to my product's linked frameworks.

**Comment by behrang** [comment]
Is there any good way to fix this problem? I don't like adding xcode project files to source repository, but if there is no other way, we can do this. Or can we make the new branch the master one?

I'll close this issue. If you want to help me, please open another issue or pull request. Thanks.

**Comment by gigaga** [comment]
Hello,

I've the same issue from the following yml file :(

```yaml
items:
- prefix: 'aa'
  endpoint:
    api: 'toto'
- prefix: 'ab'
  endpoint:
    api: 'tata'`
```

Thx

**Comment by seivan** [comment]
@gigaga Your yaml is invalid.

```
items:
- prefix: 'aa'
  endpoint:
    api: 'toto'
- prefix: 'ab'
  endpoint:
    api: 'tata'`
```
Could it be that the last "`" is a markdown typo?
