### ISSUE TITLE
Nested lists of objects is not supported. 

### ISSUE THREAD

**Issue by seivan** [behrang/YamlSwift#40]
```yaml
- GrandParent: 
  - Parent:
    - Child:
      - GrandChild:
        - name : "Skylar"
        - age : 12
```

Works on http://www.yamllint.com

This should work, the YAML spec mentions using lists of objects if you want order keys, and I'd like ordered keys.
